blank_issues_enabled: true
contact_links:
  - name: FAQ
    url: https://Zeta.com/faq/
    about: Frequently Asked Questions
  - name: Help Center
    url: https://support.Zeta.app/
    about: Help Center
  - name: Community
    url: https://community.Zeta.app/
    about: Community support, this is the place to ask questions
